export const LASER_SHOT_DELAY = 250; // In milliseconds
export const ENEMY_HEIGHT = 24;
export const ENEMY_MOVEMENT_SPEED = 100;
export const ENEMY_SHOT_DELAY = 3750;
export const PLAYER_LASER_BEAM_SPEED = 250;
export const PLAYER_LASER_LIFE_SPAN = 2000;
export const ENEMY_LASER_BEAM_SPEED = 200;
export const ENEMY_LASER_LIFE_SPAN = 3000;
export const PLAYER_GRACE_PERIOD = 1500;
